{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-fastapi-ingress
  labels:
    app: currency-converter-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:
      paths:
      - pathType: {{ .Values.ingress.pathType }}
        path: {{ .Values.ingress.path }}
        backend:
          service:
            name: {{ .Release.Name }}-currency-converter-api-service
            port:
              number: {{ .Values.service.port }}
{{- end }}